version: '3.8'
services:

  database:
    image: postgres:15.4-alpine3.18
    container_name: nimax-db
    restart: on-failure
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data/
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 1s
      timeout: 5s
      retries: 10

  backend-srv:
    build:
      context: ..
      dockerfile: ./infra/Dockerfile
    container_name: nimax-srv
    restart: on-failure
    volumes:
      - static_value:/micromarket/static/
      - media_value:/micromarket/media/
    depends_on:
      - database
    env_file:
      - .env

  nginx:
    image: nginx:1.25.2
    container_name: nimax-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - backend-srv

volumes:
  static_value:
  media_value:
  pg_data:
